[mesh]
dimension = 2
type = "quad4"

division = [100, 20, 1]
length = [5.0, 1.0, 0.25]

[boundary_condition]
dirichlet = [
  [[1, 1, 0, 0, 0, 0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [[0.0, 0.0], [0.0, 1.0], [0.0, 0.0]]],
  [[1, 1, 0, 0, 0, 0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [[5.0, 5.0], [0.0, 1.0], [0.0, 0.0]]],
]

neumann = [
  [[0.0, -1.0, 0.0], [[2.0, 3.0], [1.0, 1.0], [0.0, 10.0]]],
]

[material]
designs_0 = 0.5
penalty = 3.0
poisson = 0.3
state = "plane_strain"
type = "Elastic"
young = [0.001, 70.0]
