[mesh]
dimension = 2
type = "quad4"

division = [100, 40, 1]
length = [100.0, 40.0, 0.25]

[boundary_condition]
dirichlet = [
  [[1, 1, 0, 0, 0, 0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [[0.0, 0.0], [0.0, 40.0], [0.0, 0.0]]],
]

neumann = [
  [[0.0, -1.0, 0.0], [[48.0, 52.0], [40.0, 40.0], [0.0, 0.0]]]
]


[material]
type = "Elastic"
state = "plane_strain"
designs_0 = 0.35
penalty = 3.0
young = [0.001, 100.0]
poisson = 0.3

[this_problem]
filterR = 3.0

non_design = [
    [[1.0], [[40.0, 60.0], [30.0, 40.0], [0.0, 0.0]]],
    [[1.0e-4], [[20.0, 30.0], [15.0, 25.0], [0.0, 0.0]]],
    [[1.0e-4], [[70.0, 80.0], [15.0, 25.0], [0.0, 0.0]]],
]


